### ISSUE TITLE
Can't Make or Update the image Thumbnails

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/rmcommon#101]
Hello Edu,

After update RMcommon to the 2.3.7.0 version, I can't make or update the image thumbnails. 

I try to upload some picture as before, the pic is uploaded, but it seem, the image thumbnails do not be done. I retry also to update the thumbnails in Image section of RMcommon, but, it do not function.

This is my Xoops config:
Xoops: 2.5.9
RMcommon: 2.3.7.0
PHP: 7.1
MySql: 5.6.33
Mywords: 2.2.6.2

Thanks for reviewing.

**Comment by JustineBABY** [comment]
When I retry to update the Thumbnails in Image section, I have this mesage:

Error : Error: Undefined class constant 'MODE_HEX'

**Comment by bitcero** [comment]
Have you installed php crypt extension?

**Comment by JustineBABY** [comment]
what's this?

**Comment by JustineBABY** [comment]
What's this? I try with every browser: Firefox, Chrome, Safari, .... but it do not function.

**Comment by JustineBABY** [comment]
What's this? I try with every browser: Firefox, Chrome, Safari, .... but it do not function. Or something wrong in the new version of Xoops?

**Comment by bitcero** [comment]
Ok, problem was fixed. Please chek it and if you have any problem with this fix please inform me.

**Comment by JustineBABY** [comment]
Cool, everything seem good now.
PS: can you see this issue: https://github.com/bitcero/mywords/issues/32
the problem was detected from 2.3.6.2 version of RMcommon till now.

Thanks alot.
