### ISSUE TITLE
Errors on install with Xoops 2.6.0

### ISSUE THREAD

**Issue by cesag** [bitcero/rmcommon#11]
I get these errors when I install rmcommon 2.2.82 on Xoops 2.6.0 (modules/rmcommon/modules.php):

*Strict: Only variables should be assigned by reference in file ROOT/modules/rmcommon/loader.php line 207

Strict: call_user_func() expects parameter 1 to be a valid callback, non-static method RmcommonCorePreload::eventCoreIncludeCommonEnd() should not be called statically in file LIB/Xoops/Core/Events.php line 181

Strict: call_user_func_array() expects parameter 1 to be a valid callback, non-static method RmcommonRmcommonPreload::eventRmcommonXoopsCommonEnd() should not be called statically in file ROOT/modules/rmcommon/api/events.php line 122

Strict: call_user_func_array() expects parameter 1 to be a valid callback, non-static method Twop6RmcommonPreload::eventRmcommonXoopsCommonEnd() should not be called statically in file ROOT/modules/rmcommon/api/events.php line 122

Unknown: Class xoopssecurity not found in file ROOT/class/xoopsload.phpat line 128 in file ROOT/class/xoopsload.php line 130

Strict: Only variables should be assigned by reference in file ROOT/modules/rmcommon/modules.php line 96

**Comment by bitcero** [comment]
RMCommon, does not run in 2.6 yet. There exists a version in development, but until XOOPS is stable, it will not released.

Once rmcommon works on XOOPS 2.6 I'll inform to community.

Regards.
