### ISSUE TITLE
rmcommon on install with Xoops 2.5.7.1

### ISSUE THREAD

**Issue by cesag** [bitcero/rmcommon#14]
include_once(/modules/system/themes/redmexico/redmexico.php): failed to open stream: No such file or directory in file /modules/system/class/cpanel.php line 63

include_once(): Failed opening '/modules/system/themes/redmexico/redmexico.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in file /modules/system/class/cpanel.php line 63

**Comment by bitcero** [comment]
Please upload the folder `system` included in `rmcommon` folder to `modules/system`.

Inside `rmcommon/system` you'll find the theme for __system__ in order to enable all features from rmcommon.

When you finished you'll have `system/themes/redmexico` folder created.

**Comment by cesag** [comment]
Thank you :-) Where to place the src folder?

**Comment by bitcero** [comment]
The src folder contains the source for css and js files and have been included in order to provide the full source (LESS and js)  to edit. Note that several files (css and js) in `rmcommon/js` and `rmcommon/css` directories has been compressed.

**Comment by bitcero** [comment]
I'm closing this issue. If you have any other problem please feel free to create a new topic.
