### ISSUE TITLE
Syntax error with mysql 5.6.24

### ISSUE THREAD

**Issue by cesag** [bitcero/rmcommon#15]
Error on install:

Unable to install rmcommon. Error(s):
Installing Common Utilities

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' KEY `event` (`event`), KEY `element` (`element`), KEY `uid` (`uid`) ) ENG' at line 9

____________

Mysql version: 5.6.24

**Comment by cesag** [comment]
Same problem with mysql 5.5.43:
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '
  KEY `event` (`event`),
  KEY `element` (`element`),
  KEY `uid` (`uid`)
)' at line 9

**Comment by cesag** [comment]
I don't have this problem with rmcommon 2.2.82:
http://github.com/bitcero/rmcommon/releases/tag/v2.2.82

The difference between latest version and 2.2.82 is on latest version, you added this code in rmcommon/sql/mysql.sql:
CREATE TABLE `mod_rmcommon_notifications` (
  `id_notification` int(11) NOT NULL AUTO_INCREMENT,
  `event` varchar(50) NOT NULL,
  `element` varchar(50) NOT NULL,
  `params` varchar(50) NOT NULL,
  `uid` int(11) NOT NULL,
  `type` varchar(10) NOT NULL DEFAULT 'module',
  `date` datetime NOT NULL,
  PRIMARY KEY `id_notification`,
  KEY `event` (`event`),
  KEY `element` (`element`),
  KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by bitcero** [comment]
Yes, this is an error. The correct code must be:

```sql
CREATE TABLE IF NOT EXISTS `mod_rmcommon_notifications` (
  `id_notification` int(11) NOT NULL AUTO_INCREMENT,
  `event` varchar(50) NOT NULL,
  `element` varchar(50) NOT NULL,
  `params` varchar(50) NOT NULL,
  `uid` int(11) NOT NULL,
  `type` varchar(10) NOT NULL DEFAULT 'module',
  `date` datetime NOT NULL,
  PRIMARY KEY (`id_notification`),
  KEY `event` (`event`),
  KEY `element` (`element`),
  KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

I'm preparing the commit...
