### ISSUE TITLE
Error when updating the module

### ISSUE THREAD

**Issue by cesag** [bitcero/rmcommon#16]
I get this error when I updated the module:
Notice: Use of undefined constant _AM_SYSTEM_DBUPDATED - assumed '_AM_SYSTEM_DBUPDATED' in file /modules/system/language/english/admin/modulesadmin.php line 68

**Comment by bitcero** [comment]
the error occurs when using the rmcommon modules manager or using the standard Xoops modules manager?

**Comment by cesag** [comment]
When using the rmcommon modules manager

**Comment by bitcero** [comment]
Fixed with d9987713c18a5408c93e232d5d4f98d1b0349321. Thanks for report.
