### ISSUE TITLE
rmcommon/templates/rmc-modules.php errors

### ISSUE THREAD

**Issue by cesag** [bitcero/rmcommon#17]
After a fresh install, I get these errors when I go to modules/rmcommon/modules.php:

Notice: Undefined index: author in file /modules/rmcommon/templates/rmc-modules.php line 81
Notice: Undefined index: author_mail in file /modules/rmcommon/templates/rmc-modules.php line 82
Notice: Undefined index: author_web in file /modules/rmcommon/templates/rmc-modules.php line 83
Notice: Undefined index: author_url in file /modules/rmcommon/templates/rmc-modules.php line 84

___

My config:

PHP: 5.6.4-4ubuntu6.2
MYSQL: 5.6.25-0ubuntu0.15.04.1
XOOPS: 2.5.7.1

Xoops and the module are in english

**Comment by bitcero** [comment]
Fixing...
