### ISSUE TITLE
rmcommon update

### ISSUE THREAD

**Issue by cesag** [bitcero/rmcommon#18]
When I go to modules/rmcommon/modules.php and click to the rmcommon "update" button, I get this error:

Notice: Use of undefined constant _AM_SYSTEM_DBUPDATED - assumed '_AM_SYSTEM_DBUPDATED' in file /modules/system/language/english/admin/modulesadmin.php line 69

___

My config:

PHP: 5.6.4-4ubuntu6.2
MYSQL: 5.6.25-0ubuntu0.15.04.1
XOOPS: 2.5.7.1

Xoops and the module are in english

**Comment by bitcero** [comment]
I think that this error was fixed with last commitment (d9987713c18a5408c93e232d5d4f98d1b0349321)... anyway, I will check it...

**Comment by bitcero** [comment]
@cesag fixed now! Thank you very much for your help.
