### ISSUE TITLE
Errors when uninstalling rmcommon

### ISSUE THREAD

**Issue by cesag** [bitcero/rmcommon#19]
When I uninstall rmcommon, I get these errors:
Notice: Undefined property: stdClass::$jquery in file /modules/rmcommon/class/template.php line 77
Notice: Undefined property: stdClass::$lang in file /modules/rmcommon/loader.php line 251
Notice: Undefined property: stdClass::$theme in file /modules/rmcommon/loader.php line 282
Notice: Undefined property: stdClass::$updates in file /modules/rmcommon/loader.php line 306
Notice: Undefined property: stdClass::$cdn_jquery_url in file /modules/rmcommon/class/template.php line 376

**Comment by bitcero** [comment]
Fixed. You need to reinstall and uninstall again to see the fixes. Thank you for your help @cesag.
