### ISSUE TITLE
Problem with Module myWords by Xoops 2.6 Alpha 3

### ISSUE THREAD

**Issue by AlexL777** [bitcero/rmcommon#27]
Hello dear developer,

I use for a few days XOOPS 2.6 Alpha 3 and also wanted the modules MyWords installed. I installed it, but get this error message:

    Fatal error: Class 'MWFunctions' not found in /www/htdocs/xxxxxxxxxxx/cms/xoops26/modules/mywords/admin/header.php on line 24

What it has to do and how can you fix it? Thank you in advance.

**Comment by mambax7** [comment]
MyWords is currently not certified for XOOPS 2.6.0
Please test only modules that are included with XOOPS 2.6.0, unless you feel comfortable with PHP development. 
However, please note that all modules created by Bitcero and available here, require RMCommon, and RMCommon is not yet ported to XOOPS 2.6.0. The work has started (see here: http://xoops.org/modules/news/article.php?storyid=6710), and of course, we always welcome people who would like to help with development of XOOPS!

**Comment by bitcero** [comment]
As mambax7 says, MyWords is not ported to Xoops 2.6. I'm working on all migration but there is still no date to finish it.
