### ISSUE TITLE
Error found in rmcommon/class/htaccess.class 

### ISSUE THREAD

**Issue by mondarse** [bitcero/rmcommon#3]
I have found this waning in rmcommon/class/htaccess.class  while entering in mywords dashborad

rmcommon version 2.2.82
mywords version 2.2.4
**preg_replace(): No ending delimiter '/' found en el archivo /modules/rmcommon/class/htaccess.class.php and line 97:**
   ```html 
                preg_replace("/RewriteBase\s{1,}(.*)\n",$rb, $this->content);
   ```
Simply add ending delimiter "/" 
   ```html 
                preg_replace("/RewriteBase\s{1,}(.*)\n/",$rb, $this->content);
   ```

**Comment by bitcero** [comment]
Fixed with 0ac4861.
Thanks!!
