### ISSUE TITLE
After a while in blocks 

### ISSUE THREAD

**Issue by dalaniz130** [bitcero/rmcommon#33]
I received this error after a while I click on the blocks link on the navigator of common utilities.
Notice: Undefined variable: blocks in file /modules/rmcommon/class/blocksfunctions.php line 102
Warning: array_merge(): Argument #2 is not an array in file /modules/rmcommon/preloads/core.php line 28

**Comment by bitcero** [comment]
Verifying...

**Comment by bitcero** [comment]
Please check again

**Comment by dalaniz130** [comment]
Could you explain how do I update the running version in server with with latest commit?, I did from module_update and not change. 


     On Friday, September 25, 2015 6:48 PM, Eduardo Cortes <notifications@github.com> wrote:
   

 Please check again—

**Comment by bitcero** [comment]
Sure! download updated files from [here](https://github.com/bitcero/rmcommon/archive/master.zip) and follow instruction from [rmcommon.com](http://rmcommon.com/en/getting-started/)
