### ISSUE TITLE
By creating a new groups, following messages in screen

### ISSUE THREAD

**Issue by dalaniz130** [bitcero/rmcommon#34]
This is the screen that appear after click on the save group button:
 {"reload":"reload","type":"error","message":"Session token expired"}

It is not possible to add new group.

**Comment by dalaniz130** [comment]
If I go to system and open group all worked fine. New groups can be created.

**Comment by dalaniz130** [comment]
Sorry I close by mistake

**Comment by bitcero** [comment]
Fixing...

**Comment by bitcero** [comment]
Please check again
