### ISSUE TITLE
dalaniz

### ISSUE THREAD

**Issue by dalaniz130** [bitcero/rmcommon#38]
Hi BitCero, I was trying to send an email from ../rmcommon/users.php?action=mailer&uid=1&query=eG9vcHNfcGFnZXRpdGxlPVVzZX... I have the option to select many users and I was testing it? but is not accepting the array of users.

I receive the following error:
Fatal error: Cannot use object of type stdClass as array in /home/acueclin/public_html/acupunctureandbeauty.org/modules/rmcommon/class/mailer.php on line 63

Could you tell me how you setup phpStorm in a xoops project to add all the xoops references and dependencies in the IDE?

**Comment by bitcero** [comment]
Fixed. preparing release to solve this issue. Thanks for reporting.
