### ISSUE TITLE
Visual Editor probleme in new RMcommon

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/rmcommon#39]
Hello Bitcero!

I had just download the new update RMcommon for here (Version 2.2.9.9), and I had choose th Visual Editor to Add/Edite my article in Mywords, but when I add or edit my article, this editor do not dispay correctly as before. I try to find it, and I found a lot of change for the Tiny Editor...

You can see in the pictures below:

<img src="https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-xpl1/t31.0-8/12363025_10207976353032843_1797112822883091642_o.jpg" width=700" border="0">

<img src="https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xtf1/t31.0-8/12370955_10207976352992842_1925095732904338082_o.jpg" width=700" border="0">

This is my xoops environnement:

Xoops, 2.5.7.1
PHP: 5.5.30
Mysql: 5.1
RMcommon: 2.2.9.9
Mywords: 2.2.4.5

Thanks for your helps, and sorry for my english so "powerfull".

Justine Baby

**Comment by bitcero** [comment]
Verifying...

**Comment by JustineBABY** [comment]
thanksssssss!

**Comment by bitcero** [comment]
Fixed! I'm preparing next release to solve this issue. Thanks for reporting.

**Comment by JustineBABY** [comment]
Thanks Edo. I'm also waiting to see this release. Regards.
