### ISSUE TITLE
Warning: Use of undefined constant RMCLOCATION in cu-js-language.php

### ISSUE THREAD

**Issue by mondarse** [bitcero/rmcommon#4]
After installing advform pluging in rmcommons and trying to configure the pluging I have found this two warnings:

*Warning: Use of undefined constant RMCLOCATION - assumed 'RMCLOCATION' in the archive /modules/rmcommon/js/cu-js-language.php and line 31
Warning: Use of undefined constant RMCLOCATION - assumed 'RMCLOCATION' in the archive /modules/rmcommon/js/cu-js-language.php and line 35*

**urls is: /modules/rmcommon/plugins.php?p=advform
rmcommons version is: 2.2.8.4 production 
advform version is: 0.9.1.3 production**

´´´
<?php if ( RMCLOCATION == 'groups' ): ?>

    confirmDelete: '<?php _e('Do you really want to delete selected groups?\n\nPlease note that this action can not be undo.', 'rmcommon' ); ?>',

<?php elseif ( RMCLOCATION == 'blocks' ): ?>
´´´ 

Don't know how to solve it this time.

**Comment by bitcero** [comment]
Fixed! Will be applied with next update. Thanks again.
