### ISSUE TITLE
RSS feeds do not function

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/rmcommon#40]
Hello again Eduardo,

I come back to report you about some bug in RMcommon. The RSS Feet do not function correctly. I think that I do everything to get it working as well, but it do not. I do set in the RMcommon Option to "Enable RSS Center" and Thent I add this line to the .htaccess file: 

RewriteRule ^rss/?(.*)$ modules/rmcommon/rss.php?$1 [L]

But I have only acces to the mysite.com/rss as in the picture below:
![rss-feet](https://cloud.githubusercontent.com/assets/16358737/12038064/1f757c22-ae55-11e5-9b06-f26e03a76e05.jpg)

When I click on all of line (given by RSS of RMcommon), its will show nothing! per exemple:

mysite.com/rss?action=showfeed&mod=mywords&show=all

But when I click on all of ling (given by RSS of Xoops), they function normaly.

mysite.com/backend.php?action=showfeed&mod=mywords&show=all

This is my Xoops Config:
Xoops, 2.5.7.1
PHP: 5.5.30
Mysql: 5.1
RMcommon: 2.2.9.6
Mywords: 2.2.4.5

Thanks for your helps, and sorry for my english so "powerfull".

Justine Baby

**Comment by bitcero** [comment]
Please enable the debug mode and post the log.

**Comment by JustineBABY** [comment]
XOOPS Debugger
None All Errors (1) Deprecated (0) Queries (107) Blocks (9) Extra (6) Timers(6)

Errors
Notice: Undefined variable: xoopsUser in file /include/notification_select.php line 26

Deprecated

Queries
0.000048 - SET NAMES 'utf8'
0.000028 - SET SQL_BIG_SELECTS = 1
0.000033 - SELECT mid FROM modules WHERE dirname='rmcommon'
0.000062 - SELECT * FROM config WHERE conf_modid='3'
0.000029 - SELECT dirname FROM modules WHERE isactive='1'
0.000043 - SELECT * FROM mod_rmcommon_settings WHERE element='lightbox'
0.000047 - SELECT * FROM config WHERE (conf_modid = '0' AND conf_catid = '1') ORDER BY conf_order ASC
0.000233 - SHOW COLUMNS IN xt_themes
0.000024 - SELECT * FROM xt_themes WHERE `dir`='onfocus'
0.000031 - SELECT * FROM modules WHERE dirname = 'xthemes'
0.000027 - SELECT * FROM config WHERE (conf_modid = '4') ORDER BY conf_order ASC
0.000041 - SELECT * FROM xt_options WHERE theme=5
0.000036 - SELECT * FROM xt_menus WHERE theme=5 AND (menu='top' OR menu='main' OR menu='landing')
0.000026 - SELECT sess_data, sess_ip FROM session WHERE sess_id = 'f288d147dc2c25644c3a67500ad45bb3'
0.000031 - SELECT * FROM users WHERE uid = '3'
0.000026 - SELECT * FROM modules WHERE dirname = 'rmcommon'
0.000033 - SELECT * FROM config WHERE (conf_modid = '3') ORDER BY conf_order ASC
0.000070 - DELETE FROM protector_access WHERE expire < UNIX_TIMESTAMP()
0.000119 - SELECT COUNT(*) FROM protector_access WHERE ip='82.224.94.221' AND request_uri='/rss?action=showfeed&mod=mywords&show=all'
0.000092 - SELECT COUNT(*) FROM protector_access WHERE ip='82.224.94.221'
0.000066 - INSERT INTO protector_access SET ip='82.224.94.221',request_uri='/rss?action=showfeed&mod=mywords&show=all',expire=UNIX_TIMESTAMP()+'60'
0.000030 - SELECT * FROM config WHERE (conf_modid = '0' AND conf_catid = '3') ORDER BY conf_order ASC
0.000028 - SELECT DISTINCT gperm_itemid FROM group_permission WHERE gperm_name = 'block_read' AND gperm_modid = 1 AND gperm_groupid IN (1)
0.000028 - SELECT b.* FROM newblocks b, block_module_link m WHERE m.block_id=b.bid AND b.isactive=1 AND b.visible=1 AND m.module_id IN (0,3) AND b.bid IN (9,8,6,5,4,2,1,17,18,20,21,22,25,29,30,31,33) ORDER BY b.weight, m.block_id
0.000027 - SELECT * FROM mod_rmcommon_blocks_positions WHERE active=1
0.000036 - SELECT DISTINCT gperm_itemid FROM group_permission WHERE (gperm_name = 'rmblock_read') AND gperm_modid = 1 AND gperm_groupid IN (1,0)
0.000034 - SELECT b.* FROM mod_rmcommon_blocks b, mod_rmcommon_blocks_assignations m WHERE m.bid=b.bid AND b.isactive=1 AND b.visible=1 AND m.mid IN (0,3) AND b.bid IN (66,3,7,10,11,12,13,14,15,16,19,40,24,23,26,27,28,32,35,36,51,41,44,43,46,49,52,53,54,55,56,60,61,62,63,64,65,67,79,77,68,78,70,73,72,80,81,82,83,85,84,86,87,88,90,91,92,93,94,95,96,97,98,100,99,101,102,103) AND canvas IN (21,22,23) ORDER BY b.weight,b.bid
0.000273 - SHOW COLUMNS IN mod_rmcommon_blocks
0.000024 - SELECT COUNT(*) FROM online WHERE online_uid=3
0.000067 - UPDATE online SET online_updated=1451413946, online_module = 3 WHERE online_uid = 3
0.000068 - SELECT * FROM online
0.000054 - SELECT COUNT(*) FROM online WHERE online_module = '3'
0.000057 - SELECT COUNT(*) FROM online WHERE online_uid=3
0.000038 - UPDATE online SET online_updated=1451413946, online_module = 3 WHERE online_uid = 3
0.000021 - SELECT * FROM online
0.000020 - SELECT COUNT(*) FROM online WHERE online_module = '3'
0.000027 - SELECT * FROM modules WHERE dirname = 'mywords'
0.000031 - SELECT * FROM config WHERE (conf_modid = '5') ORDER BY conf_order ASC
0.000026 - SELECT * FROM mod_mywords_categories WHERE parent='0' ORDER BY id_cat DESC
0.000022 - SELECT * FROM mod_mywords_categories WHERE parent='31' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='67' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='54' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='53' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='50' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='34' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='33' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='32' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='11' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='27' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='52' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='49' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='48' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='47' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='46' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='12' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='26' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='56' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='20' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='19' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='18' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='15' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='25' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='57' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='10' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='4' ORDER BY id_cat DESC
0.000021 - SELECT * FROM mod_mywords_categories WHERE parent='24' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='61' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='60' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='59' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='58' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='9' ORDER BY id_cat DESC
0.000022 - SELECT * FROM mod_mywords_categories WHERE parent='23' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='51' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='45' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='44' ORDER BY id_cat DESC
0.000021 - SELECT * FROM mod_mywords_categories WHERE parent='43' ORDER BY id_cat DESC
0.000023 - SELECT * FROM mod_mywords_categories WHERE parent='42' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='41' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='40' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='39' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='8' ORDER BY id_cat DESC
0.000022 - SELECT * FROM mod_mywords_categories WHERE parent='22' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='68' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='66' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='65' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='64' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='63' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='62' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='38' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='37' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='36' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='35' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='7' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='17' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='14' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='16' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='13' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='21' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='6' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='5' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='3' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='2' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='1' ORDER BY id_cat DESC
0.000039 - SELECT * FROM mod_mywords_tags LIMIT 99
0.000038 - SELECT * FROM mod_mywords_editors ORDER BY name
0.000048 - SELECT * FROM mod_mywords_posts WHERE visibility = 'public' AND status='publish' ORDER BY pubdate DESC LIMIT 0,5
0.000304 - SHOW COLUMNS IN mod_mywords_posts

**Comment by JustineBABY** [comment]
XOOPS Debugger
None All Errors (1) Deprecated (0) Queries (107) Blocks (9) Extra (6) Timers(6)

Errors
Notice: Undefined variable: xoopsUser in file /include/notification_select.php line 26

Deprecated

Queries
0.000048 - SET NAMES 'utf8'
0.000028 - SET SQL_BIG_SELECTS = 1
0.000033 - SELECT mid FROM modules WHERE dirname='rmcommon'
0.000062 - SELECT * FROM config WHERE conf_modid='3'
0.000029 - SELECT dirname FROM modules WHERE isactive='1'
0.000043 - SELECT * FROM mod_rmcommon_settings WHERE element='lightbox'
0.000047 - SELECT * FROM config WHERE (conf_modid = '0' AND conf_catid = '1') ORDER BY conf_order ASC
0.000027 - SELECT * FROM config WHERE (conf_modid = '4') ORDER BY conf_order ASC
0.000041 - SELECT * FROM xt_options WHERE theme=5
0.000036 - SELECT * FROM xt_menus WHERE theme=5 AND (menu='top' OR menu='main' OR menu='landing')
0.000026 - SELECT sess_data, sess_ip FROM session WHERE sess_id = 'f288d147dc2c25644c3a67500ad45bb3'
0.000031 - SELECT * FROM users WHERE uid = '3'
0.000026 - SELECT * FROM modules WHERE dirname = 'rmcommon'
0.000033 - SELECT * FROM config WHERE (conf_modid = '3') ORDER BY conf_order ASC
0.000070 - DELETE FROM protector_access WHERE expire < UNIX_TIMESTAMP()
0.000119 - SELECT COUNT(*) FROM protector_access WHERE ip='82.224.94.221' AND request_uri='/rss?action=showfeed&mod=mywords&show=all'
0.000092 - SELECT COUNT(*) FROM protector_access WHERE ip='82.224.94.221'
0.000066 - INSERT INTO protector_access SET ip='82.224.94.221',request_uri='/rss?action=showfeed&mod=mywords&show=all',expire=UNIX_TIMESTAMP()+'60'
0.000030 - SELECT * FROM config WHERE (conf_modid = '0' AND conf_catid = '3') ORDER BY conf_order ASC
0.000028 - SELECT DISTINCT gperm_itemid FROM group_permission WHERE gperm_name = 'block_read' AND gperm_modid = 1 AND gperm_groupid IN (1)
0.000028 - SELECT b.* FROM newblocks b, block_module_link m WHERE m.block_id=b.bid AND b.isactive=1 AND b.visible=1 AND m.module_id IN (0,3) AND b.bid IN (9,8,6,5,4,2,1,17,18,20,21,22,25,29,30,31,33) ORDER BY b.weight, m.block_id
0.000027 - SELECT * FROM mod_rmcommon_blocks_positions WHERE active=1
0.000036 - SELECT DISTINCT gperm_itemid FROM group_permission WHERE (gperm_name = 'rmblock_read') AND gperm_modid = 1 AND gperm_groupid IN (1,0)
0.000034 - SELECT b.* FROM mod_rmcommon_blocks b, mod_rmcommon_blocks_assignations m WHERE m.bid=b.bid AND b.isactive=1 AND b.visible=1 AND m.mid IN (0,3) AND b.bid IN (66,3,7,10,11,12,13,14,15,16,19,40,24,23,26,27,28,32,35,36,51,41,44,43,46,49,52,53,54,55,56,60,61,62,63,64,65,67,79,77,68,78,70,73,72,80,81,82,83,85,84,86,87,88,90,91,92,93,94,95,96,97,98,100,99,101,102,103) AND canvas IN (21,22,23) ORDER BY b.weight,b.bid
0.000273 - SHOW COLUMNS IN mod_rmcommon_blocks
0.000024 - SELECT COUNT(*) FROM online WHERE online_uid=3
0.000067 - UPDATE online SET online_updated=1451413946, online_module = 3 WHERE online_uid = 3
0.000068 - SELECT * FROM online
0.000054 - SELECT COUNT(*) FROM online WHERE online_module = '3'
0.000057 - SELECT COUNT(*) FROM online WHERE online_uid=3
0.000038 - UPDATE online SET online_updated=1451413946, online_module = 3 WHERE online_uid = 3
0.000021 - SELECT * FROM online
0.000020 - SELECT COUNT(*) FROM online WHERE online_module = '3'
0.000027 - SELECT * FROM modules WHERE dirname = 'mywords'
0.000031 - SELECT * FROM config WHERE (conf_modid = '5') ORDER BY conf_order ASC
0.000026 - SELECT * FROM mod_mywords_categories WHERE parent='0' ORDER BY id_cat DESC
0.000022 - SELECT * FROM mod_mywords_categories WHERE parent='31' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='67' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='54' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='53' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='50' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='34' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='33' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='32' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='11' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='27' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='52' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='49' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='48' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='47' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='46' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='12' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='26' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='56' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='20' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='19' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='18' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='15' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='25' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='57' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='10' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='4' ORDER BY id_cat DESC
0.000021 - SELECT * FROM mod_mywords_categories WHERE parent='24' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='61' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='60' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='59' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='58' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='9' ORDER BY id_cat DESC
0.000022 - SELECT * FROM mod_mywords_categories WHERE parent='23' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='51' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='45' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='44' ORDER BY id_cat DESC
0.000021 - SELECT * FROM mod_mywords_categories WHERE parent='43' ORDER BY id_cat DESC
0.000023 - SELECT * FROM mod_mywords_categories WHERE parent='42' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='41' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='40' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='39' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='8' ORDER BY id_cat DESC
0.000022 - SELECT * FROM mod_mywords_categories WHERE parent='22' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='68' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='66' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='65' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='64' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='63' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='62' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='38' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='37' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='36' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='35' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='7' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='17' ORDER BY id_cat DESC
0.000019 - SELECT * FROM mod_mywords_categories WHERE parent='14' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='16' ORDER BY id_cat DESC
0.000020 - SELECT * FROM mod_mywords_categories WHERE parent='13' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='21' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='6' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='5' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='3' ORDER BY id_cat DESC
0.000017 - SELECT * FROM mod_mywords_categories WHERE parent='2' ORDER BY id_cat DESC
0.000018 - SELECT * FROM mod_mywords_categories WHERE parent='1' ORDER BY id_cat DESC
0.000039 - SELECT * FROM mod_mywords_tags LIMIT 99
0.000038 - SELECT * FROM mod_mywords_editors ORDER BY name
0.000048 - SELECT * FROM mod_mywords_posts WHERE visibility = 'public' AND status='publish' ORDER BY pubdate DESC LIMIT 0,5
0.000304 - SHOW COLUMNS IN mod_mywords_posts

**Comment by bitcero** [comment]
Thank you... I'm checking the problem...

**Comment by bitcero** [comment]
I've published a new version of Common Utilities. Please try it and tell me if this problem has been fixed. Regards.

**Comment by JustineBABY** [comment]
Ok, I'll do it now!

Thanks alot, Eduardo.

**Comment by JustineBABY** [comment]
Aiiii...

I replaced the old RMcommon folder by the new downloaded master one, I have this line when I go to the site:

Fatal error: require(): Failed opening required 'class/Psr4ClassLoader.php' (include_path='.:/usr/lib/php5.5') in /homepages/htdocs/www/modules/rmcommon/loader.php on line 251

and nothing els.
thanks for reply.

**Comment by mambax7** [comment]
I copied over the new files, and one of the errors I am getting are:
0.001031 - SELECT dir FROM mod_rmcommon_plugins WHERE status=1
Error number: 1146
Error message: Table '257bit2.x1f8_mod_rmcommon_plugins' doesn't exist
Is this a bug, or did I do something wrong? I did run the update of RMC...

**Comment by bitcero** [comment]
@mambax7 What was the previous version? Please try to uninstall and the install again the module

**Comment by bitcero** [comment]
@JustineBABY Please verify that you've copied all files from "class" folder. If not, try to copy again files. Also verify that you've downloaded last version of master branch.
