### ISSUE TITLE
Post content has been "provided" when "Visual Editor"  choosed

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/rmcommon#42]
Hello,

Finaly, I Can update everything to the new version: RMcommon, Mywords,... also the plugin in RMcommon. they look so great, thanks for your work. But i found alot of Bugs... for this 2.3.1.2 version of RMcommon.

First one, the Visual Editor probleme is comeback. When I want to edit an post. I didn't found the content post as before. This probleme come only with "Visual Editor" and "HTML Editor", but for the "Simple Editor' and "Markdown Editor", everything seem good.

You can see in the picture:
![visual-edittor-4](https://cloud.githubusercontent.com/assets/16358737/12135827/3095b020-b441-11e5-868c-892a7cc41f31.jpg)

This is my new xoops config:

Xoops: 2.5.7.2
PHP: 5.5.30
Mysql: 5.1.73
RMcommon: 2.3.1.2
Mywords: 2.2.4.9

Best regards
JBB

**Comment by JustineBABY** [comment]
Hello,

I confirm the same problem with the module Qpages.

Regards.
JBB

**Comment by bitcero** [comment]
Verified... this error occurs with visual editor... fixing.
