### ISSUE TITLE
RSS feeds still do not function

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/rmcommon#44]
Hello one more,

As before, in this version of RMcommon, the RSS center still do not function. This is the issue posted #40 (copy-paste here):

I do set in the RMcommon Option to "Enable RSS Center" and Thent I add this line to the .htaccess file: 

RewriteRule ^rss/?(.*)$ modules/rmcommon/rss.php?$1 [L]

But I have only acces to the mysite.com/rss as in the picture below, and all the link here can't be gone:
![rss-feet](https://cloud.githubusercontent.com/assets/16358737/12038064/1f757c22-ae55-11e5-9b06-f26e03a76e05.jpg)

This is my new xoops config:

Xoops: 2.5.7.2
PHP: 5.5.30
Mysql: 5.1.73
RMcommon: 2.3.1.3
Mywords: 2.2.4.9

Best regards
JBB

**Comment by bitcero** [comment]
Line must be RewriteRule ^rss/?(*)$ modules/rmcommon/rss.php?$1 [L]

**Comment by JustineBABY** [comment]
Not good, now I have the hold site like this:

> Internal Server Error

> The server encountered an internal error or misconfiguration and was unable to complete your request.

> Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

> More information about this error may be available in the server error log.

> Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

But the rewritter for the Mywords module is also: 

> RewriteRule ^news/?(.*)$ modules/mywords/index.php [L]

Thanks for reply.
JBB

**Comment by JustineBABY** [comment]
If I put this link

> mysite.com/**backend.php**?action=showfeed&mod=mywords&show=all

Everything seem function as well!

JBB

**Comment by bitcero** [comment]
Have you tried with `RewriteRule ^rss/?(.*)$ modules/rmcommon/rss.php$1 [L]` ? If it is possible, can you send me the content of your htaccess file to email i.bitcero (at) gmail.com?

**Comment by JustineBABY** [comment]
Ok, with the line

> RewriteRule ^rss/?(.*)$ modules/rmcommon/rss.php$1 [L]

Now, it work as very well. So you can change also the RSS notification in RMcommon admin, because the line before, i have copied from there.

Thanks, Now I close the issue.
JBB

**Comment by bitcero** [comment]
Perfect!!

**Comment by JustineBABY** [comment]
can you get a look there:
https://github.com/bitcero/mywords/issues/3

thanks.
