### ISSUE TITLE
How to set sort order and position on list for categories and sites in qpages?

### ISSUE THREAD

**Issue by panwac** [bitcero/rmcommon#53]
I'm testing qpages and now I'm trying to find a possibility to change a sort order for pages (categories too). In admin panel there is an option "Set order", but I don't see any effect of that. Any suggestions? ;)

Vbr

Piotr

**Comment by bitcero** [comment]
Please use **[QuickPages repo page](https://github.com/redmexico/qpages/issues)** to report and ask about this module.

https://github.com/redmexico/qpages/issues
