### ISSUE TITLE
I can not add menus in themes

### ISSUE THREAD

**Issue by kostas4k** [bitcero/rmcommon#55]
I try to add menu after the last upgrade, in both ethernial and OnFocus but without success.

I do not know if related the errors that appear in page debug:

Unknown: Method RMTemplate::add_local_script is deprecated. Use RMTemplate::add_script instead. in file /modules/rmcommon/class/template.php line 1402
Unknown: Method RMTemplate::add_local_script is deprecated. Use RMTemplate::add_script instead. in file /modules/rmcommon/class/template.php line 1402
Unknown: Method RMTemplate::add_local_script is deprecated. Use RMTemplate::add_script instead. in file /modules/rmcommon/class/template.php line 1402
Notice: Undefined index: main in file /modules/xthemes/templates/xt_navigation.php line 28
Warning: Invalid argument supplied for foreach() in file /modules/xthemes/templates/xt_navigation.php line 28
Notice: Undefined index: type in file /modules/rmcommon/class/template.php line 1025
Notice: There are not any service installed for avatar! in file /modules/rmcommon/class/helpers/Services.php line 80

**Comment by kostas4k** [comment]
Some info about my system
XOOPS: 2.5.7.2
PHP: 5.5.26
MySQL: 5.6.25

**Comment by bitcero** [comment]
Hi... This issue must be reported in **[xThemes](https://github.com/bitcero/xthemes/)** repository. Will be fixed with next commit.
