### ISSUE TITLE
Imágenes no se guardan en Common Utilities

### ISSUE THREAD

**Issue by ryuaka** [bitcero/rmcommon#57]
Cuando tratas de subir imágenes a una categoría de imágenes en Common Utilities 2.3.1.9. estas no se cargan; se queda con el mensaje de "Redimensionar Imágenes - Por favor, no cierres la ventana hasta que el proceso de redimensionar haya terminado" y de ahí no pasa más.

He probado varias configuraciones y en todas se queda en el mismo paso.

La configuración del server es la siguiente:

PHP: 5.6
XOOPS: 2.5.7.2
Common Utilities 2.3.1.9.

**Comment by bitcero** [comment]
Verificando...

**Comment by ryuaka** [comment]
En el servidor online, si está cerrado el sitio. De ahí en un servidor local, tengo instalado XOOPS para hacer pruebas de módulos y ese está completamente abierto y aún así sucede los mismo. 

Por otro lado, en ese mismo servidor local, también tengo otro sitio que está cerrado y con Common Utilities 2.2.9.6. y da el error.

**Comment by ryuaka** [comment]
He encontrado la solución a este problema. Al parecer y por alguna razón, no cargaba el archivo **jquery-ui.min.js** necesario para hacer el escalado a pesar de que viene establecido en el archivo de common utilities (theme.php).

La solución es instalar el plugin lightbox en common utilities y con eso todo vuelve a la normalidad. Salvo el server en donde esta hospedado el sitio de pruebas que me devuelve un 500 server internal error (ya es asunto del servidor), pero en pruebas locales ha funcionado muy bien.

**Comment by bitcero** [comment]
Esto no debería ocurrir... voy a verificar el problema.

**Comment by bitcero** [comment]
Corregido con el commit c75c259... para aplicar en la próxima actualización automática...
