### ISSUE TITLE
XoopsEditorHandler::getList() should not be called statically

### ISSUE THREAD

**Issue by AlexL777** [bitcero/rmcommon#58]
Hello Developers,

I have only one problem with the new modules Rmcommon and displays this error when accessing the Admin Dashboard.

    Deprecated
    XoopsEditorHandler::getList() should not be called statically.
    'Database::getInstance();' is deprecated since XOOPS 2.5.4, please use  'XoopsDatabaseFactory::getDatabaseConnection();' instead.

Can it somehow fixed or it comes from Xoops installation itself.

I have PHP 5.6, Xoops 2.5.7.2 and the last mySQL version on the managed server.

**Comment by bitcero** [comment]
This error seems to be related to Xoops itself. Common Utilities does not use XoopsEditorHandler. Maybe some module is generating this warning. Can you tell me please the version of rmcommon that you are using? Also the location (page in dashboard) where you are getting this error...

**Comment by geekwright** [comment]
> XoopsEditorHandler::getList() should not be called statically.

That is definitely coming from a module calling it, not from core itself. The code in *class/xoopseditor/xoopseditor.php* even includes this note:
```
/*
    Do NOT use this method statically, please use
    $editor_handler = XoopsEditorHandler::getInstance();
     $result = array_flip($editor_handler->getList());
*/

**Comment by bitcero** [comment]
@AlexL777 you need to check what module are you using that is generating this error... Thanks @geekwright for your clarification!

**Comment by AlexL777** [comment]
Not so easy to find out which modules it can be. I have now uninstalled up to 5 modules, where I thought they could be.

Now I've only got under **/modules/rmcommon** in the browser this error:

    XoopsEditorHandler :: getList () Should not be called statically

**Comment by AlexL777** [comment]
Everything good again and I Common Utilities have repeatedly uploaded to the server. Then I downloaded the latest version of the official website and sent to the server.

Now the Xoops backend seems to work.

Only SEO URLS with MyWords not work. I have to look even know what it is.

Thanks for your help.

I will probably install the 5 uninstalled modules again, because it was perhaps not in it.

If I have problems, I rise like.
