### ISSUE TITLE
Groups Management does not Edit or Delete group

### ISSUE THREAD

**Issue by dalaniz130** [bitcero/rmcommon#65]
I am using Common Utilities 2.3.1.5 and XOOPS 2.5.7.1., php ver 5.6.14, mysql 5.07.
When I create a new group (DataEntry) in xoops/modules/rmcommon/groups.php, is not editing or deleting those new groups. When I hit Edit will show a New Group form, and when I hit the butoon Delete, nothing happen. Thanks

**Comment by bitcero** [comment]
Verified... problem will be fixed in next commit and the patch will be published in next update. Thanks for report.
