### ISSUE TITLE
rmc-navigation-pages.php no funciona

### ISSUE THREAD

**Issue by ryuaka** [bitcero/rmcommon#68]
Al aparecer la barra de navegación en la página principal de MyWords; si quiero ir de la página 1 a la página 2 ó a la última página me aparece el siguiente mensaje:

`ERROR 404. Document not Found`

El debugger no marca ningún error. Tengo la última versión de MyWords la 2.2.5.4 y de Common Utilities la versión 2.3.2.5 que hasta ahora me ha funcionado bien, pero no se si tenga algún error en mi tema o si algo esté pasando con el módulo.

**Comment by bitcero** [comment]
Ok... verificando

**Comment by ryuaka** [comment]
Probando en sitio online...

**Comment by ryuaka** [comment]
Verificado bitcero, funciona haciendo lo que dijiste, activé la reescritura URL en Common Utilities y también configuré MyWords, y ahora no da problemas en ese aspecto. Muchas gracias por tu apoyo.

**Comment by bitcero** [comment]
Muy bien. cierro el hilo.
