### ISSUE TITLE
error al ingresar al panel principal

### ISSUE THREAD

**Issue by markosc** [bitcero/rmcommon#69]
con la ultima actualización  y instalando xoops  2.5.8 ó 2.5.7 (con la 2.5.6  no lo sé porque no encontré versión anterior) con php 5.4 / 5.3 /5.5 
cuando instalo rmcommon y instento ingresar al panel principal a site.com/modules/rmcommon/ sale un mesaje que mi dominio no funciona, y al activar el degbug sale nuevamente ese mensaje del error de conección del dominio,  solo da ese error cuando instalo  rmcommon, así mismo cuando instalo la versión estable de 2.2.82 , lo curioso cuando quieres ver el control panel de redmexico en la configuracion del sistema no aparece como si no existiera la plantilla solo están las demas por defecto.

**Comment by markosc** [comment]
el problema es al instalar la ultima versión de mywords, con la versión 2.2.4.5 funciona perfecto

**Comment by bitcero** [comment]
Verificando y reparando...

**Comment by bitcero** [comment]
Comprueba 40fa8e5 y verifica si presenta algún error.
