### ISSUE TITLE
Can't add any picture

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/rmcommon#73]
Hello,

Thanks for the change for Xoops 2.5.8 and PHP 7 Ready. But we have more problem:

Second problem, we can't not add the pic (in RMcommon or in Mywords module. It seem the problem become the "DivisionByZeroError: Modulo by zero". You can see the pic below:

![cant-add-pic](https://cloud.githubusercontent.com/assets/16358737/15670781/88c73008-2727-11e6-9eae-ff684ba6d237.jpg)

![my-xoops-config](https://cloud.githubusercontent.com/assets/16358737/15670785/8d626aec-2727-11e6-824e-977133424267.jpg)

With the best.

**Comment by bitcero** [comment]
I was unable to reproduce this error... can you provide more details?

Browser:
OS:
Previous actions:

**Comment by JustineBABY** [comment]
Browser: Chrome and Firefox
OS: Windows
Previous action: Nothing, becaus it a news installation of RMcommon, and update from 2.3.2.5 to 2.3.2.7

You can see in the video by this link:

[https://1fichier.com/?jpmnwks1ye](url)

With the best.

**Comment by JustineBABY** [comment]
Now, when I try to update thumbnails, I have also this screen:

![cant-add-pic](https://cloud.githubusercontent.com/assets/16358737/15738338/105fdbd0-28ab-11e6-86a2-8200d78b8d33.jpg)

When I try to edit an image and replace this image to an another category, I have this creen with the message: Error: Call to undefined method RMImageResizer::addError()

![cant-replace-image](https://cloud.githubusercontent.com/assets/16358737/15738654/92eda892-28ac-11e6-9757-f751ced6734f.jpg)

**my xoops config:**
xoops: 2.5.8
rmcommon: 2.3.2.8
mywords: 2.2.5.5
php: 7.0.7
mysql: 5.6.30

Thanks for fixing this bug.
with the best.

**Comment by JustineBABY** [comment]
I found the solution!
Thanks.

**Comment by bitcero** [comment]
Perfect... can you share your solution to help others?
