### ISSUE TITLE
NO se puede subir Imagenes

### ISSUE THREAD

**Issue by markosc** [bitcero/rmcommon#76]
cuando voy a mywords o de forma individual en rmcommon y deseo agregar una imagen o una imagen del articulo, puedo ver las pestaña de las categorías pero no aparece el boton de "explorar" donde es para agregar la imagen para subir, y si tengo ya categorias creadas...

XOOPS: 2.5.8
PHP: 5.6.22
MYSQL: 5.5.45
Common Utilities: 2.3.2.8

**Comment by markosc** [comment]
solo funciona con Google Chrome, ya que con Opera, Firefox y Edge no aparece el boton de explorar para subir la imagen....

**Comment by bitcero** [comment]
El problema se debe al componente basado en flash. Estoy preparando la migración a un nuevo componente.

**Comment by bitcero** [comment]
Hola @markosc. Recién actualicé la rama Helium con el nuevo componente para carga de imágenes. Si deseas probarlo y apoyarme para detectar problemas puedes [descargar este archivo](https://github.com/bitcero/rmcommon/archive/helium.zip).

**Comment by bitcero** [comment]
Este es el aspecto que tiene ahora el control de cargas:

![captura de pantalla 2016-06-22 a las 10 06 14 a m](https://cloud.githubusercontent.com/assets/1305172/16271814/182a44a2-3861-11e6-8ebb-f7beaadaba9d.png)

![captura de pantalla 2016-06-22 a las 10 06 52 a m](https://cloud.githubusercontent.com/assets/1305172/16271820/1e18a4a8-3861-11e6-838e-ddebb4df38b0.png)
