### ISSUE TITLE
Gestor de imagenes no permite insertar en selección

### ISSUE THREAD

**Issue by markosc** [bitcero/rmcommon#77]
en el administrador de imagenes si quiero agregar 3 o imagenes al mismo tiempo se congela, y no aparece la opción para agregar la cuarta imagen...
asi mismo cuando inserto aparece un tag de "undefined"
![insertando iamgenes de seleccion](https://cloud.githubusercontent.com/assets/16872280/17075920/5c914b20-5069-11e6-9de3-9d889aeee802.png)
![3ra-imagen](https://cloud.githubusercontent.com/assets/16872280/17075919/5c9076d2-5069-11e6-90c0-4f1b53ccbc5d.png)
Xoops 2.5.8 
Rmcommon (master)
mywords (master)

**Comment by bitcero** [comment]
Este problema se ha corregido en la rama Helium. En unos dias combinaré los cambios con master.
