### ISSUE TITLE
Just 3 minor notices & one unknown bug report.

### ISSUE THREAD

**Issue by aceman11** [bitcero/rmcommon#87]
XOOPS: 2.5.8 
PHP: 5.6.20
MYSQL: 5.6.33
## Rmcommon-master.zip / Common Utilities 2.3.4.1 was downloaded today and installed on fresh xoops 2.5.8 site with pm, profile & protector already installed.

Notice: You must provide the caption and value when add a new cell to Counter Widget in file /modules/rmcommon/widgets/Counter.php line 133

Unknown: Only variables should be assigned by reference in file /modules/system/themes/redmexico/redmexico.php line 68

Notice: Undefined property: stdClass::$helium_logo in file /modules/rmcommon/themes/helium/admin-gui.php line 178

Notice: Undefined property: stdClass::$helium_xoops_metas in file /modules/rmcommon/themes/helium/admin-gui.php line 190

Thanks!
Ace

BTW; This is a game changer for xoops & is gorgeous looking. You rock man!

**Comment by bitcero** [comment]
Verifying... thanks

**Comment by aceman11** [comment]
Very cool here is one more unknown. I have a lot of notices as well. I figure I better not bug you with them. Anyway...
---
Unknown: call_user_func_array() expects parameter 1 to be a valid callback, non-static method QpagesRmcommonPreload::eventRmcommonRegisterIconProvider() should not be called statically in file /modules/rmcommon/api/events.php line 122

Regards
Ace

**Comment by bitcero** [comment]
This is a notice from QPages that I'll fix in next commit (_integration with PHP 7_).
