### ISSUE TITLE
Problem after update to 2.3.6.2: Can't Edit the article in HTML view

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/rmcommon#92]
Hello Edu,

I've updated the RMcommon to the new version, now I have the 2.3.6.2, Thanks,

But I have some problems:
I've choosed the Visual Editor TinyMCE as my principal Editor, but in HTLM view, I can't edit anything in the article.  

This is my Xoops config:
Xoops: 2.5.8.1
RMcommon: 2.3.6.2
PHP: 7.1
MySql: 5.6.33
Mywords: 2.2.5.9

Thanks for reviewing.

**Comment by bitcero** [comment]
Verifying
