### ISSUE TITLE
Blank page for public web, and mywords admin

### ISSUE THREAD

**Issue by JustineBABY** [bitcero/rmcommon#95]
Hello Edu,

After update RMcommon to the 2.3.6.5 version, and also update Mywords to the 2.2.6.2 version, I have the  blank page for The Website (public side) and for Mywords Admin.

This is the problem in debug mod: 
Fatal error: Cannot redeclare RMUtilities::get_count() in /web/modules/rmcommon/class/utilities.php on line 57

This is my Xoops config:
Xoops: 2.5.8.1
RMcommon: 2.3.6.5
PHP: 7.1
MySql: 5.6.33
Mywords: 2.2.6.2

Thanks for reviewing.

**Comment by bitcero** [comment]
I can't reproduce the error. What other modules do you have installed? The error seems to be a duplicate include for utilities.php file, but I'll need more information.

**Comment by JustineBABY** [comment]
I have installed only these modules (Xoops, RMcommon, Mywords, xTheme) for online testing. 

May be I do something wrong during the update process? Because the update process in RMcommon seem do not function, so i have to replace all the old files by the news files from the updated module package, and than I have update the module by clicking in the Modules adminstration (in Xoops and also RMcommon). 

Can you remember me if this process is correct.

**Comment by bitcero** [comment]
Verify that file `xoops_data/caches/xoops_cache/xoops_..._system_modules_active.php` have a line with **mywords** value and another for **rmcommon**.

Example:
```php
return array (
  0 => 'system',
  1 => 'rmcommon',
  2 => 'mywords',
);
```
Sometimes this file is not updated by xoops and blank page screen occurs.

**Comment by bitcero** [comment]
BTW, the update process is correct.

**Comment by JustineBABY** [comment]
Yes, I have it :
xoops_k85nhg25_system_modules_active.php

> 1528772153
> return array (
>   0 => 'system',
>   1 => 'rmcommon',
>   2 => 'mywords',
>   3 => 'xthemes',
> );

But I have alway the blank page on the public side, and for the post page of Mywords module (I mean only this page: _modules/mywords/admin/posts.php?op=edit_  or _op=new_)

## This is the debug in public side:

Fatal error: Cannot redeclare RMUtilities::get_count() in /web/modules/rmcommon/class/utilities.php on line 57

_None All Errors (4) Deprecated (0) Queries (43) Blocks (7) Extra (2) Timers(5)_

**Errors**
Unknown: Methods with the same name as their class will not be constructors in a future version of PHP; gettext_reader has a deprecated constructor in file /modules/rmcommon/class/gettext/gettext.php line 36
Unknown: Methods with the same name as their class will not be constructors in a future version of PHP; StringReader has a deprecated constructor in file /modules/rmcommon/class/gettext/streams.php line 48
Unknown: Methods with the same name as their class will not be constructors in a future version of PHP; FileReader has a deprecated constructor in file /modules/rmcommon/class/gettext/streams.php line 83
Unknown: Methods with the same name as their class will not be constructors in a future version of PHP; CachedFileReader has a deprecated constructor in file /modules/rmcommon/class/gettext/streams.php line 145 

## This is the debug in Mywords post page:

Fatal error: Cannot redeclare RMUtilities::get_count() in /web/modules/rmcommon/class/utilities.php on line 57

_None All Errors (5) Deprecated (0) Queries (110) Blocks (0) Extra (2) Timers(6)_

**Errors**
Unknown: Methods with the same name as their class will not be constructors in a future version of PHP; gettext_reader has a deprecated constructor in file /modules/rmcommon/class/gettext/gettext.php line 36
Unknown: Methods with the same name as their class will not be constructors in a future version of PHP; StringReader has a deprecated constructor in file /modules/rmcommon/class/gettext/streams.php line 48
Unknown: Methods with the same name as their class will not be constructors in a future version of PHP; FileReader has a deprecated constructor in file /modules/rmcommon/class/gettext/streams.php line 83
Unknown: Methods with the same name as their class will not be constructors in a future version of PHP; CachedFileReader has a deprecated constructor in file /modules/rmcommon/class/gettext/streams.php line 145
Unknown: Non-static method AdvformPluginRmcommonPreload::eventRmcommonFormLoader() should not be called statically in file /modules/rmcommon/api/events.php line 122

**Comment by bitcero** [comment]
can you confirm same error with new version?

**Comment by JustineBABY** [comment]
Hello,
for this probleme of blank page, seem OK now. but still have another bugs...
but I close the issue.

**Comment by bitcero** [comment]
Ok... please let me know about the other bugs...
